version: "3.9"
services:
  # DATABASES #
  test:
    image: mongo:latest
    container_name: test
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test_database
    networks:
      - backend
    labels:
      - "container_group=TIG"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # DevOps #
  eureka-server:
    image: eureka:latest
    restart: always 
    container_name: eureka-server
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - backend
    labels:
      - "container_group=TIG"
    depends_on:
      test:
        condition: service_healthy
  
  gateway-service:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway-service
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_URI=${EUREKA_URI}
    networks:
      - backend
    labels:
      - "container_group=TIG"
  
  # SERVICES #
  person-service:
    image: person:0.0.1-SNAPSHOT
    depends_on:
      - eureka-server
      - gateway-service
      - test
    links:
      - test
    ports:
      - 8180:8180
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - EUREKA_URI=${EUREKA_URI}
    networks:
      - backend
    labels:
      - "container_group=TIG"
  
  # influxdb #
  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - backend
    labels:
      - "container_group=TIG"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # grafana #
  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://${GRAFANA_DOMAIN}:3000
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - backend
    labels:
      - "container_group=TIG"
  
  # simulado #
  simulado:
    image: ldabiralai/simulado:latest
    container_name: simulado
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
    networks:
      - backend
    labels:
      - "container_group=TIG"
  
  # k6 #
  k6:
    image: loadimpact/k6:0.28.0
    container_name: k6
    ports:
      - "6565:6565"
    volumes:
      - ./shared/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/${INFLUXDB_DB}
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - backend
    labels:
      - "container_group=TIG"

networks:
  backend:
    driver: bridge

volumes:
  grafana_storage:
