version: "3.9"
services:
  # DATABASES #
  test:
    image: mongo:latest
    container_name: test
    ports:
      - 27018:27018
    environment:
      - MONGO_INITDB_DATABASE=test_database
    networks:
      - backend
    labels:
      - "container_group=TIG" 
  
  # DevOps #
  #eureka-server:
    #image: eureka
    #restart: always 
    #container_name: eureka
    #ports:
      #- '8761:8761'
    #environment:
      #- SPRING_PROFILES_ACTIVE=dev
    #networks:
      #- backend
    #labels:
      #- "container_group=TIG"
  
  #gateway-service:
    #image: gateway:0.0.1-SNAPSHOT
    #container_name: gateway-service
    #depends_on:
      #- eureka-server
    #ports:
      #- 8080:8080
    #environment:
      #- SPRING_PROFILES_ACTIVE=dev
    #networks:
      #- backend
    #labels:
      #- "container_group=TIG"
  
  # SERVICES #
  #person-service:
    #image: person:0.0.1-SNAPSHOT
    #depends_on:
      #- eureka-server
      #- gateway-service
    #links:
      #- test
    #ports:
      #- 8180:8180
    #environment:
      #- SPRING_PROFILES_ACTIVE=dev
      #- SPRING_DATA_MONGODB_URI=mongodb://test:27018/test_database 
    #networks:
      #- backend
    #labels:
      #- "container_group=TIG"
  
  # influxdb #
  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=xxxxxxx
    #volumes:
      #- influxdb:$PWD/var/lib/influxdb
    networks:
      - backend
    labels:
      - "container_group=TIG" 
  
  # grafana #
  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.2.3
      - GF_SECURITY_ADMIN_PASSWORD=xxxxxxxx
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=ejemplo.com
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    links:
      - influxdb
    volumes:
      #- ./shared/grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      #- ./shared/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      #- ./shared/grafana:/etc/grafana/provisioning/
      - grafana:$PWD/var/lib/grafana
  
  # simulado #
  simulado:
    image: ldabiralai/simulado:latest
    container_name: simulado
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
    networks:
      - backend
    labels:
      - "container_group=TIG"
  
  # k6 #
  k6:
    image: loadimpact/k6:0.28.0
    container_name: k6
    ports:
      - "6565:6565"
    volumes:
      - ./shared/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - backend
    labels:
      - "container_group=TIG"

networks:
  backend:

volumes:
  grafana: {}
  #influxdb: {}
